FROM node:22-alpine

WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_GOOGLE_JAVASCRIPT_MAP_API
ARG VITE_API_BASE_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_GOOGLE_JAVASCRIPT_MAP_API=$VITE_GOOGLE_JAVASCRIPT_MAP_API
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build && ls -la dist && test -f dist/index.html

EXPOSE 8080
CMD ["node", "server.js"]
